### ISSUE TITLE
Backend features

### ISSUE THREAD

**Issue by onkoe** [CS3203-GroupF/engage#33]
Please leave your requirements below.

- Interact with and manage the database.
- Provide "login" functionality to the frontend.
  - IMPORTANT: NEED SPECIFICS!
- Search functionality for frontend.
  - IMPORTANT: NEED SPECIFICS!

**Comment by mitchelltawk** [comment]
Organizations and their information ( organization name, description, and contact information) should populate when the user types in keywords into the search bar.

**Comment by OfficerClucks** [comment]
You should be able to add new tags to the orgs

**Comment by KyleTarczon** [comment]
I don't believe org descriptions should populate when we are in the process of searching. Only once you have clicked on an organization should it give you details about that org. I am hoping for a working log-in system, a working search recommender, and a back-end database to fill both of these functions. I will have 150 clubs in the SQL Code by tomorrow night btw.

**Comment by KyleTarczon** [comment]
Anything else like looks, clicks, and HTML stuff should be frontend, please reply to this comment with any menial frontend work that needs to get done and I will look into it!
